### ISSUE TITLE
I adapted your script into a one-click script

### ISSUE THREAD

**Issue by gaifeng8864** [d4rk50ul1/klipper-on-android#11]
Great work, your script saved me a lot of time. I wanted to go a step further, so I adapted your script into a one-click script. However, my level is limited, and there are many steps that can be added to the script. Are you interested in continuing this work, let us make
Is "klipper-on-android" more convenient?
https://github.com/gaifeng8864/klipper-on-android

**Comment by d4rk50ul1** [comment]
Hey @gaifeng8864  thank you so much for your update. i'm in fact wiping my android installation and following yours to see how it goes!
